services:
  mssql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your@StrongPass1"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql/data